version: '3.9'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/django_orm
    environment:
      - DJANGO_SETTINGS_MODULE=orm.settings
    command: python manage.py runserver 0.0.0.0:8000
